### ISSUE TITLE
Rename new `Bcrypt` and `OTP` libraries.

### ISSUE THREAD

**Issue by mrstegeman** [hummingbird-project/hummingbird-auth#52]
I just pulled down the new RC tag and ended up with a broken build, because our project uses [`swift-otp`](https://github.pie.apple.com/swift-server/swift-otp), which also has an `OTP` library.

Could these new libraries be renamed with a `Hummingbird` prefix?

**Comment by adam-fowler** [comment]
Are you trying to import both OTP libraries?

**Comment by mrstegeman** [comment]
Thanks, I had no idea that feature even existed. I was able to solve it like this:
```
        .product(
          name: "HummingbirdAuth",
          package: "hummingbird-auth",
          moduleAliases: ["OTP": "HummingbirdOTP"]
        ),
```

**Comment by dharknes** [comment]
This issue needs to be reopened. `moduleAliases` doesn't work for Xcode projects.

**Comment by adam-fowler** [comment]
> This issue needs to be reopened. moduleAliases doesn't work for swift packages in Xcode managed through Package.swift.

Are you experiencing this as an issue?

**Comment by dharknes** [comment]
Yep. Xcode seems to ignore the Package.swift `moduleAliases` so projects that include both swift-otp and hummingbird can't being developed in Xcode.

**Comment by adam-fowler** [comment]
Is `swift-otp` an internal Apple package?
