### ISSUE TITLE
Session Cookie Expiration

### ISSUE THREAD

**Issue by kaybutter** [hummingbird-project/hummingbird-auth#63]
Hi, I'm currently trying to figure out how to use SessionStorage correctly (Using hummingbird 2.0 and hummingbird-auth 2.0.0-RC3). 

My assumption was that if I passed in an `expiresIn` value when saving the session, I'd be able to extend the session lifetimes. But it looks like that the expiration date is only saved in the database, and doesn't actually affect the lifetime of the session cookie. Without setting an explicit expiration date on the cookie, it just expires whenever the browser decides that the session is over (I haven't quite figured out when that is). So, if I set an `expiresIn` value of 30 days, the cookie still expires way earlier.

So here's my question: Is this intentional? I can work around it taking the cookie returned by `sessionStorage.save` and creating a new cookie based on that with a proper expiration date. But I thought, I'd check if I'm overseeing something here.

**Comment by adam-fowler** [comment]
With the current setup you'd have to return a response with a new set-cookie header. 

The session code is being reworked to make it easier to work with so I would wait for that to be merged first. See #61

**Comment by kaybutter** [comment]
Sounds good. Then I'll wait for these changes 👍
