### ISSUE TITLE
Cookies security Options in the new Session API

### ISSUE THREAD

**Issue by thoven87** [hummingbird-project/hummingbird-auth#71]
I have been testing the new Session API, it's been nice so far. I do wonder if there should be options allowed to be passed in different environments context. Say, in production we would like to se a session cookie `sameSite` as strict to prevent XSS and CSRF attack. 

I think this option should be available given that setting a session is mundane task.

**Comment by adam-fowler** [comment]
Good point

**Comment by adam-fowler** [comment]
#72

**Comment by adam-fowler** [comment]
Merged

**Comment by thoven87** [comment]
> Merged

My computer should arrive either this weekend or early next week. I will test and report. I think the same site enum still needs updated to allow strict as an option and also allows one to set a cookie as both strict and secure.
