### ISSUE TITLE
Cookies Serialization/DeSerialization issue

### ISSUE THREAD

**Issue by thoven87** [hummingbird-project/hummingbird-auth#76]
Suppose one has a basic AppContext as Follow

```swift
enum Role: Int16, Codable {
    case admin = 0
    case user = 1
}

struct User: Codable {
    let id: UUID
    let username: String
    let role: Role
}

typealias AppRequestContext = BasicSessionRequestContext<UUID, User>
```

At some point in the future, one decides to add some fancy session enum to manage auth state:

```swift
enum AuthnSession: Codable {
    case registrationStart(username: String)
    case registrationFinished(verificationChallenge: String)
    case authenticationStart(username: String)
    case authenticationFinished(challenge: String, code: Int16)
   
    .........
}

struct ApplicationRequestContext: AuthRequestContext, SessionRequestContext, RemoteAddressRequestContext, RequestContext, RouterRequestContext {

    typealias Identity = User
    
    let channel: Channel?
    var coreContext: CoreRequestContextStorage
    var identity: Identity?
    var routerContext: HummingbirdRouter.RouterBuilderContext
    var sessions: SessionContext<AuthSession>
    var remoteAddress: SocketAddress? {
        guard let channel else { return nil }
        return channel.remoteAddress
    }

    init(source: Source) {
        self.channel = source.channel
        self.coreContext = .init(source: source)
        self.identity = nil
        self.sessions = .init()
        self.routerContext = .init()
    }
}
```

The server will throw 500 indefinitely for requests which contain the first session implementation until the session data is deleted from the database or a user clears their session data from their web browser.

I think the storage persist [should not swallow the decoding error](https://github.com/hummingbird-project/hummingbird-postgres/blob/main/Sources/HummingbirdPostgres/PostgresPersistDriver.swift#L130) and/or the session should be considered "invalid" and throw 401 instead of 500.

**Comment by adam-fowler** [comment]
If persist is swallowing the error, how can it be returning a 500 response?

**Comment by thoven87** [comment]
> If persist is swallowing the error, how can it be returning a 500 response?

I think the issue might be upstream in how the session middleware behaves? When I looked at this issue a couple weeks ago, I was confused I didn't see the decoding error. I should finally have a computer today, I will provide better debugging step on how to reproduce.

**Comment by adam-fowler** [comment]
It throws the decoding error which goes all the way up to the HTTP server handler which doesn't know what to do with it so it returns a 500 response.

**Comment by adam-fowler** [comment]
We have an inconsistency in the different persist frameworks on how they respond to asking for the wrong object type. Redis and Postgres throw a Decoding error, Memory return nil. I'm going to change this so they all throw an error `PersistError.invalidType` and then respond correctly in the SessionMiddleware

**Comment by adam-fowler** [comment]
This should fix it https://github.com/hummingbird-project/hummingbird-auth/pull/77

**Comment by thoven87** [comment]
> It throws the decoding error which goes all the way up to the HTTP server handler which doesn't know what to do with it so it returns a 500 response.

This makes sense now.
> If the session doesn't convert it should probably expire the cookie.
I think this should be the correct behavior here. 
Do you think it would be a good idea to introduce secrets for session id?

> We have an inconsistency in the different persist frameworks on how they respond to asking for the wrong object type. Redis and Postgres throw a Decoding error, Memory return nil. I'm going to change this so they all throw an error PersistError.invalidType and then respond correctly in the SessionMiddleware

>This should fix it https://github.com/hummingbird-project/hummingbird-auth/pull/77
EDIT: Once I have updated the Postgres repo, but that needs a Hummingbird release first. Too many packages 😓

I apologize for starting this chain reaction. I will be able to help soon :(

**Comment by adam-fowler** [comment]
> I apologize for starting this chain reaction. I will be able to help soon :(

Don't worry about it. This is a totally valid bug. Once you get the Postgres, Redis persist PRs merged and released I think we are good. HB and HBAuth have the relevant changes released already.

**Comment by thoven87** [comment]
> > I apologize for starting this chain reaction. I will be able to help soon :(
> 
> Don't worry about it. This is a totally valid bug. Once you get the Postgres, Redis persist PRs merged and released I think we are good. HB and HBAuth have the relevant changes released already.

Thank You!
