### ISSUE TITLE
Update session cookie expiration

### ISSUE THREAD

**Issue by kaybutter** [hummingbird-project/hummingbird-auth#78]
Hi, I'm building a webauthn authentication flow. As part of that, I create a very short-lived session when the authentication begins and then I update the session with a longer lifetime when the authentication finishes.

Unfortunately, it looks like `SessionMiddleware` currently ignores that updated lifetime in this part:
``` swift
// if session has been edited then store new session
if sessionData.edited {
    do {
        try await self.sessionStorage
            .update(
                session: sessionData.object,
                expiresIn: sessionData.expiresIn,
                request: request
            )
    } catch let error as SessionStorage<Context.Session>.Error where error == .sessionDoesNotExist {
        let cookie = try await self.sessionStorage.save(
            session: sessionData.object,
            expiresIn: sessionData.expiresIn ?? self.defaultSessionExpiration
        )
        // this is a new session so set the "Set-Cookie" header
        response.headers[values: .setCookie].append(cookie.description)
    }
}
```
It looks like it only sends an updated cookie if there is no existing session, so my extended lifetime is ignored.

Is this intended behavior or should I be able to update the session lifetime somehow?

**Comment by adam-fowler** [comment]
Ok I guess it should probably update the cookie at that point.
Although currently if the client uses the cookie again after the new expiration date the storage will not return it as it has expired. So in effect the expiration update still occurs, it is just not reported back to the client.

**Comment by adam-fowler** [comment]
Good point, it won't work for extending the lifetime of a cookie. I'll look into it

**Comment by adam-fowler** [comment]
#79
